loop:
    data_step: 1000
    n: 20
    start_data: 10000
    verbose: 1
    epochs_cnt: 240000
model_params:
    model_name: EfficientNetB0
    input_shape: (256, 256, 3)
    optimizer: tf.keras.optimizers.Adam
    loss: tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
    metrics: sparse_categorical_accuracy
data_loading_params:
    name: custom
    batch_size: 128
    norm_func: normalize_img
    resize: (256, 256)
    custom_dir: 10_food_classes_all_data
    validation_or_test: test